/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/GameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PlayersScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/RandomFen`; params?: Router.UnknownInputParams; } | { pathname: `/components/oldGame`; params?: Router.UnknownInputParams; } | { pathname: `/store/gamesSlices`; params?: Router.UnknownInputParams; } | { pathname: `/store/playersSlices`; params?: Router.UnknownInputParams; } | { pathname: `/store/rootReducer`; params?: Router.UnknownInputParams; } | { pathname: `/store/store`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/GameScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/PlayersScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/RandomFen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/oldGame`; params?: Router.UnknownOutputParams; } | { pathname: `/store/gamesSlices`; params?: Router.UnknownOutputParams; } | { pathname: `/store/playersSlices`; params?: Router.UnknownOutputParams; } | { pathname: `/store/rootReducer`; params?: Router.UnknownOutputParams; } | { pathname: `/store/store`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/GameScreen${`?${string}` | `#${string}` | ''}` | `/PlayersScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/RandomFen${`?${string}` | `#${string}` | ''}` | `/components/oldGame${`?${string}` | `#${string}` | ''}` | `/store/gamesSlices${`?${string}` | `#${string}` | ''}` | `/store/playersSlices${`?${string}` | `#${string}` | ''}` | `/store/rootReducer${`?${string}` | `#${string}` | ''}` | `/store/store${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/GameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PlayersScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/RandomFen`; params?: Router.UnknownInputParams; } | { pathname: `/components/oldGame`; params?: Router.UnknownInputParams; } | { pathname: `/store/gamesSlices`; params?: Router.UnknownInputParams; } | { pathname: `/store/playersSlices`; params?: Router.UnknownInputParams; } | { pathname: `/store/rootReducer`; params?: Router.UnknownInputParams; } | { pathname: `/store/store`; params?: Router.UnknownInputParams; };
    }
  }
}
